"""
Django settings for kinetic project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from django.contrib.messages import constants as messages


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sessions',
    'django.contrib.sitemaps',
    'pages.apps.PagesConfig',
    'contact.apps.ContactConfig',
    'accounts.apps.AccountsConfig',
    'events.apps.EventsConfig',
    'blog',
    'middleware',
#    'robots'

    
]

#from django.contrib.sites.models import Site  # Add this import at the top

from dotenv import load_dotenv
load_dotenv()  # Loads variables from .env file


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fy9lnzq_x^q7l8xy_zutp3bf4=wd1j&dft9!h!zsj#a(gt5cum'

# SECURITY WARNING: don't run with debug turned on in production!


DEBUG = True

# Trust the X-Forwarded-For header from Nginx
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Set the trusted proxies (e.g., Nginx running on localhost)
if DEBUG:
    ALLOWED_HOSTS = ['*']  # Allow all hosts in development
else:
    ALLOWED_HOSTS = [
    '127.0.0.1',          # Localhost
    'localhost',          # Localhost by name
    '152.42.229.97',  # Your production domain
    'www.your-production-domain.com', # WWW subdomain
    '192.168.1.100',      # Local network IP
    'subdomain.your-production-domain.com', # Subdomain example
    'jackieng.hk',       # Allow all subdomains of example.com
    ]  # Replace with your domain

# Trust the X-Forwarded-For header from Nginx
from django.conf import settings

if not settings.DEBUG:
    settings.MIDDLEWARE.insert(0, 'django.middleware.http.SetRemoteAddrFromForwardedFor')



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middleware.access_log_middleware.AccessLogMiddleware',
]

ROOT_URLCONF = 'kinetic.urls'

SITE_ID = 1     # in Admin, update the Site to domain name e.g. localhost, kinetic.hk 

CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8001',  
    'http://127.0.0.1:8001/admin', 
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kinetic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'kinetic_dev',
        'USER' : 'dbadmin',
        'PASSWORD' : '1234',
        'HOST' : 'localhost',

    }
}
"""

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),

    }
}


# Domain settings
DOMAIN = os.environ.get('DOMAIN', 'localhost')
SITE_URL = f'http://{DOMAIN}'
# Robots/sitemap settings
ROBOTS_SITEMAP_URLS = [
    f'{SITE_URL}/sitemap.xml',
]

ROBOTS_CACHE_TIMEOUT = 60*60*24  # Cache for 24 hours
# domain determined by SITE_ID
ROBOTS_USE_SCHEME_IN_HOST = True  # Use https:// in URLs


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Hong_Kong'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'kinetic/static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MESSAGE_TAGS = {
    messages.ERROR : 'danger',
    messages.SUCCESS: 'success',
    messages.INFO: 'info',
    messages.WARNING: 'warning',
}

"""Purpose: This backend is useful for development purposes. It prints email messages to the console instead of sending them.
Use Case: When you want to test your email functionality without actually sending emails. You can see the email content in your terminal.

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
"""
# Email configuration # 
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Your SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'wagor71@gmail.com'
EMAIL_HOST_PASSWORD = 'yrre eqap clgo nkqt'  #gmail app password

#EMAIL_HOST_USER = 'jackieng5000@yahoo.com'
#EMAIL_HOST_PASSWORD = 'pansylinda@1'

