# Generated by Django 4.2 on 2025-01-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='title',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
    ]
