# Generated by Django 4.2 on 2025-04-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='updated_by',
        ),
    ]
